version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgres://oqcmbtbg:RPcknsddspsp4uWDM-t-6QsodjbcodsosWrIjbvcobodbIEn7Bo@elmer.db.elephantsql.com:5432/cpcdspmbtbg
